name: Build, Check Style and Deploy

on:
  # For style checks only
  push:
    branches: [ main ]
    paths-ignore:
      - 'Documentation/**'
  
  # For manual documentation generation
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  style-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build with StyleCop analysis
        run: dotnet build --no-restore /p:TreatWarningsAsErrors=true /p:EnforceCodeStyleInBuild=true

  build-docs:
    # Only run this job on manual trigger
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install, build, and upload your site
        uses: withastro/action@v3
        with:
          path: ./Documentation

  deploy-docs:
    # Only run this job on manual trigger and after build-docs
    if: github.event_name == 'workflow_dispatch'
    needs: build-docs
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4